# Site settings
title: Brett Marcinkiewicz
description: Brett Marcinkiewicz's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog

# User settings
username: Brett Marcinkiewicz
user_description: Junior at Umass Lowell majoring in Computer Science. I'm available for Co-op from January-August 2018.
user_title: Student & Software Developer
email: brettmarcin@gmail.com
github_username:  BrettMarcin
linkedin_username: brett-marcinkiewicz

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
